Repository Automattic/stories-android, pull requests merged in 2021-05, with the labels that each got.

#687 Remove remaining synthetics from ComposeLoopFrameActivity
  stories/src/main/java/com/wordpress/stories/compose/ComposeLoopFrameActivity.kt
Labels: [Type] Task

#652 Using lib in WPAndroid video compression scenario
  mp4compose/src/main/java/com/daasuu/mp4compose/Rotation.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/VideoFormatMimeType.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/AudioChannelWithSP.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/AudioComposer.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/BaseAudioChannel.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/ComposerProvider.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/Listener.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/Mp4Composer.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/Mp4ComposerBasic.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/Mp4ComposerEngineBasic.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/RemixAudioComposer.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/RemixAudioComposerBasic.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/SonicAudioProcessor.java
  mp4compose/src/main/java/com/daasuu/mp4compose/composer/VideoComposer.kt
  mp4compose/src/main/java/com/daasuu/mp4compose/logger/AndroidLogger.java
  mp4compose/src/main/java/com/daasuu/mp4compose/logger/Logger.java
  mp4compose/src/main/java/com/daasuu/mp4compose/source/DataSource.java
  mp4compose/src/main/java/com/daasuu/mp4compose/source/FilePathDataSource.java
  photoeditor/src/main/java/com/automattic/photoeditor/PhotoEditor.kt
Labels: [Type] Enhancement, mp4composer

#693 Invalidate cache
  gradle/wrapper/gradle-wrapper.properties
Labels: Tooling

#697 Add configure plugin 0.6.0
  .circleci/config.yml
  .configure
  .configure-files/gradle.properties.enc
  .configure-files/release.jks.enc
  build.gradle
  gradle.properties.enc
Labels: Tooling

#699 Updates configure plugin to 0.6.1
  build.gradle
Labels: Tooling
